name: Deploy ADF

on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./adfprojectpipeline/ARMTemplateForFactory.json
          parameters: >
            ./adfprojectpipeline/ARMTemplateParametersForFactory.json
            factoryName=${{ secrets.ADF_FACTORY_NAME }}
          deploymentName: adf-deployment
